// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://dzjunaaooisoempesesv.supabase.co';
// Use a harmless fallback key so the app can load in demo mode without crashing when env vars are missing.
const supabaseKey = import.meta.env.VITE_SUPABASE_KEY || 'public-anon-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseKey as string,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Disable email confirmation requirements
      confirmEmail: false,
    }
  }
);